### ISSUE TITLE
1S VTX signal loss,  not working as expected

### ISSUE THREAD

**Issue by AfterburnerRC** [D3VL/Avatar-Firmware-Updates#19]
Hello,  I am seeing a significant signal loss with a new Happy Model Mobula7 BNF that has the 1S VTX in it.  When flying in my house and between rooms approximately no more than 20 feet I will get FPV video smearing followed by the RED border in the goggle feed.  Goggles and VTX are on the latest 28.32.10 firmware,  with Reset All completed,  500mw,  Standby Mode ON as I am using the BF OSD.  I have tried all available channels via FCC hack and no difference in performance.  I am using the Black Walksnail goggles with stock antennas and I have also tried the Walksnail patch antennas with no difference.  As soon as I take off within 5 feet the signal bar drops 1 bar and continues to fluctuate during the flight within a 60 foot flight pattern, sometimes to 0 bars.  When outside I get perfect signal and can fly up to 80m without signal loss.  The issue seemed to be the penetration of the walls inside the house.  I have also turned OFF any wifi in my house to rule this out and NO difference in video performance.   Franco Fpvsardegna on the Walksnail FB group has reported he is seeing the same issue and recommends downgrading to 27.32.10 firmware.

**Comment by D3VL-Jack** [comment]
Please direct your concerns to official WalkSnail support routes - this repo just hosts fw files, we have no influence to thier functionality.
